#-- Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
  toc_levels:     2..5
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # use_coderay:    false
highlighter:      rouge
excerpt_separator: "<!--more-->"

#-- Permalinks
permalink:        pretty

future:           true

#-- Setup
title:            TU Delft MSc Geomatics graduation thesis
url:              "https://3d.bk.tudelft.nl"
baseurl:          "/courses/geo2020"


